name: doin_fx
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8

  bloc: 9.2.0
  flutter_bloc: 9.1.1
  get_it: 7.6.7

  auto_route: 11.1.0   # âœ… runtime (exists)

  http: 1.6.0

  flutter_form_builder: 10.2.0
  form_builder_validators: 11.2.0
  dio: 5.9.0
  intl_phone_field: 3.2.0
  flutter_secure_storage: 9.2.2
  bot_toast: 4.1.3
  flutter_svg: 2.2.3
  webview_flutter: 4.2.1
  socket_io_client: 3.1.3 
  # flutter_form_builder: 10.2.0
  font_awesome_flutter: 10.12.0
  dotted_border: 2.1.0
  file_picker: 10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.10.4
  auto_route_generator: 10.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pairs/
    - assets/images/ticketTypes/
    - assets/images/kyc/


  # commands to generate the routes
  # flutter pub run build_runner build --delete-conflicting-outputs
  # flutter pub run auto_route_generator
